const supabase = require("./config/supabaseAdmin");

const medicines = [
  {
    medicine_name: "Paracetamol 500mg",
    generic_name: "Paracetamol",
    brand: "Biogesic",
    type: "Tablet",
    dosage: "500mg",
    unit_of_measure: "Tablet",
    stock_level: 100,
    batch_number: "BATCH-PCM-001",
    expiry_date: "2026-12-31",
  },
  {
    medicine_name: "Ibuprofen 200mg",
    generic_name: "Ibuprofen",
    brand: "Advil",
    type: "Tablet",
    dosage: "200mg",
    unit_of_measure: "Tablet",
    stock_level: 100,
    batch_number: "BATCH-IBU-001",
    expiry_date: "2026-12-31",
  },
  {
    medicine_name: "Amoxicillin 500mg",
    generic_name: "Amoxicillin",
    brand: "Amoxil",
    type: "Capsule",
    dosage: "500mg",
    unit_of_measure: "Capsule",
    stock_level: 100,
    batch_number: "BATCH-AMX-001",
    expiry_date: "2026-06-30",
  },
  {
    medicine_name: "Cetirizine 10mg",
    generic_name: "Cetirizine",
    brand: "Zyrtec",
    type: "Tablet",
    dosage: "10mg",
    unit_of_measure: "Tablet",
    stock_level: 100,
    batch_number: "BATCH-CTZ-001",
    expiry_date: "2026-12-31",
  },
  {
    medicine_name: "Loperamide 2mg",
    generic_name: "Loperamide",
    brand: "Imodium",
    type: "Capsule",
    dosage: "2mg",
    unit_of_measure: "Capsule",
    stock_level: 100,
    batch_number: "BATCH-LPR-001",
    expiry_date: "2026-12-31",
  },
  {
    medicine_name: "Mefenamic Acid 500mg",
    generic_name: "Mefenamic Acid",
    brand: "Ponstan",
    type: "Capsule",
    dosage: "500mg",
    unit_of_measure: "Capsule",
    stock_level: 100,
    batch_number: "BATCH-MFA-001",
    expiry_date: "2026-12-31",
  },
  {
    medicine_name: "Omeprazole 20mg",
    generic_name: "Omeprazole",
    brand: "Losec",
    type: "Capsule",
    dosage: "20mg",
    unit_of_measure: "Capsule",
    stock_level: 100,
    batch_number: "BATCH-OMP-001",
    expiry_date: "2026-09-30",
  },
  {
    medicine_name: "Salbutamol 2mg",
    generic_name: "Salbutamol",
    brand: "Ventolin",
    type: "Tablet",
    dosage: "2mg",
    unit_of_measure: "Tablet",
    stock_level: 100,
    batch_number: "BATCH-SBT-001",
    expiry_date: "2026-12-31",
  },
  {
    medicine_name: "Loratadine 10mg",
    generic_name: "Loratadine",
    brand: "Claritin",
    type: "Tablet",
    dosage: "10mg",
    unit_of_measure: "Tablet",
    stock_level: 100,
    batch_number: "BATCH-LRD-001",
    expiry_date: "2026-12-31",
  },
  {
    medicine_name: "Metformin 500mg",
    generic_name: "Metformin",
    brand: "Glucophage",
    type: "Tablet",
    dosage: "500mg",
    unit_of_measure: "Tablet",
    stock_level: 100,
    batch_number: "BATCH-MTF-001",
    expiry_date: "2026-12-31",
  },
  {
    medicine_name: "Amlodipine 5mg",
    generic_name: "Amlodipine",
    brand: "Norvasc",
    type: "Tablet",
    dosage: "5mg",
    unit_of_measure: "Tablet",
    stock_level: 100,
    batch_number: "BATCH-AML-001",
    expiry_date: "2026-12-31",
  },
  {
    medicine_name: "Losartan 50mg",
    generic_name: "Losartan",
    brand: "Cozaar",
    type: "Tablet",
    dosage: "50mg",
    unit_of_measure: "Tablet",
    stock_level: 100,
    batch_number: "BATCH-LSR-001",
    expiry_date: "2026-12-31",
  },
  {
    medicine_name: "Ciprofloxacin 500mg",
    generic_name: "Ciprofloxacin",
    brand: "Ciprobay",
    type: "Tablet",
    dosage: "500mg",
    unit_of_measure: "Tablet",
    stock_level: 100,
    batch_number: "BATCH-CPR-001",
    expiry_date: "2026-06-30",
  },
  {
    medicine_name: "Doxycycline 100mg",
    generic_name: "Doxycycline",
    brand: "Vibramycin",
    type: "Capsule",
    dosage: "100mg",
    unit_of_measure: "Capsule",
    stock_level: 100,
    batch_number: "BATCH-DXC-001",
    expiry_date: "2026-12-31",
  },
  {
    medicine_name: "Cotrimoxazole 800/160mg",
    generic_name: "Sulfamethoxazole/Trimethoprim",
    brand: "Bactrim",
    type: "Tablet",
    dosage: "800/160mg",
    unit_of_measure: "Tablet",
    stock_level: 100,
    batch_number: "BATCH-CTX-001",
    expiry_date: "2026-12-31",
  },
  {
    medicine_name: "Phenylephrine 10mg",
    generic_name: "Phenylephrine",
    brand: "Neozep",
    type: "Tablet",
    dosage: "10mg",
    unit_of_measure: "Tablet",
    stock_level: 100,
    batch_number: "BATCH-PHL-001",
    expiry_date: "2026-12-31",
  },
  {
    medicine_name: "Ascorbic Acid 500mg",
    generic_name: "Vitamin C",
    brand: "Celin",
    type: "Tablet",
    dosage: "500mg",
    unit_of_measure: "Tablet",
    stock_level: 100,
    batch_number: "BATCH-VTC-001",
    expiry_date: "2027-06-30",
  },
  {
    medicine_name: "Multivitamins",
    generic_name: "Multivitamins",
    brand: "Enervon",
    type: "Tablet",
    dosage: "1 tablet",
    unit_of_measure: "Tablet",
    stock_level: 100,
    batch_number: "BATCH-MVT-001",
    expiry_date: "2027-06-30",
  },
  {
    medicine_name: "Antacid Suspension",
    generic_name: "Aluminum Hydroxide/Magnesium Hydroxide",
    brand: "Kremil-S",
    type: "Suspension",
    dosage: "10ml",
    unit_of_measure: "Bottle",
    stock_level: 100,
    batch_number: "BATCH-ANT-001",
    expiry_date: "2026-12-31",
  },
  {
    medicine_name: "Diphenhydramine 25mg",
    generic_name: "Diphenhydramine",
    brand: "Benadryl",
    type: "Capsule",
    dosage: "25mg",
    unit_of_measure: "Capsule",
    stock_level: 100,
    batch_number: "BATCH-DPH-001",
    expiry_date: "2026-12-31",
  },
];

async function seedMedicines() {
  console.log(`Seeding ${medicines.length} medicines...`);

  const { data, error } = await supabase
    .from("medicines")
    .insert(medicines)
    .select();

  if (error) {
    console.error("Error seeding medicines:", error.message);
    process.exit(1);
  }

  console.log(`Successfully seeded ${data.length} medicines (each with stock: 100).`);
  process.exit(0);
}

seedMedicines();
