-- Migration: Add invitation_status column to users table
-- This supports the email activation flow where personnel receive an invite
-- link instead of having a password auto-generated by the admin.

ALTER TABLE public.users
  ADD COLUMN IF NOT EXISTS invitation_status TEXT NOT NULL DEFAULT 'ACTIVE'
  CHECK (invitation_status IN ('PENDING', 'ACTIVE'));

-- Set all existing users (already logged in at least once) to ACTIVE
UPDATE public.users SET invitation_status = 'ACTIVE' WHERE invitation_status IS NULL;

COMMENT ON COLUMN public.users.invitation_status IS
  'PENDING = invite email sent, user has not yet activated account; ACTIVE = account activated by user';
